version: "3.7"
services:
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    container_name: "mongodb"
    ports:
      - 27017:27017
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo_db:app_db

